module.exports = [
    { src: 'karina.jpg', name: 'Карина', age: 7 },
    { src: 'alexander.jpg', name: 'Александр', age: 5 },
    { src: 'bona.jpg', name: 'Екатерина', age: 3 },
    { src: 'ichi.jpg', name: 'Анна', age: 7 },
    { src: 'lloyd.jpg', name: 'Игорь', age: 4 },
    { src: 'luiza.jpg', name: 'Луиза', age: 9 },
    { src: 'max.jpg', name: 'Maкс', age: 6 },
    { src: 'mona.jpg', name: 'Ольга', age: 3 },
    { src: 'naru.jpg', name: 'Евгения', age: 7 },
    { src: 'ramdan.jpg', name: 'Руслан', age: 8 },
    { src: 'rikki-austin.jpg', name: 'Рикки Остин', age: 3 },
    { src: 'tucker.jpg', name: 'Дмитрий', age: 9 },
    { src: 'uriel.jpg', name: 'Михаил', age: 6 },
    { src: 'zoe.jpg', name: 'Зоя', age: 2 },
    { src: 'karina.jpg', name: 'Карина', age: 7 },
    { src: 'alexander.jpg', name: 'Александр', age: 5 },
    { src: 'bona.jpg', name: 'Екатерина', age: 3 },
    { src: 'ichi.jpg', name: 'Анна', age: 7 },
    { src: 'lloyd.jpg', name: 'Игорь', age: 4 },
    { src: 'luiza.jpg', name: 'Луиза', age: 9 },
    { src: 'max.jpg', name: 'Maкс', age: 6 },
    { src: 'mona.jpg', name: 'Ольга', age: 3 },
    { src: 'naru.jpg', name: 'Евгения', age: 7 },
    { src: 'ramdan.jpg', name: 'Руслан', age: 8 },
    { src: 'rikki-austin.jpg', name: 'Рикки Остин', age: 3 },
    { src: 'tucker.jpg', name: 'Дмитрий', age: 9 },
    { src: 'uriel.jpg', name: 'Михаил', age: 6 },
    { src: 'zoe.jpg', name: 'Зоя', age: 2 },
    { src: 'karina.jpg', name: 'Карина', age: 7 },
    { src: 'alexander.jpg', name: 'Александр', age: 5 },
    { src: 'bona.jpg', name: 'Екатерина', age: 3 },
    { src: 'ichi.jpg', name: 'Анна', age: 7 },
    { src: 'lloyd.jpg', name: 'Игорь', age: 4 },
    { src: 'luiza.jpg', name: 'Луиза', age: 9 },
    { src: 'max.jpg', name: 'Maкс', age: 6 },
    { src: 'mona.jpg', name: 'Ольга', age: 3 },
    { src: 'naru.jpg', name: 'Евгения', age: 7 },
    { src: 'ramdan.jpg', name: 'Руслан', age: 8 },
    { src: 'rikki-austin.jpg', name: 'Рикки Остин', age: 3 },
    { src: 'tucker.jpg', name: 'Дмитрий', age: 9 },
    { src: 'uriel.jpg', name: 'Михаил', age: 6 },
    { src: 'zoe.jpg', name: 'Зоя', age: 2 },
    { src: 'karina.jpg', name: 'Карина', age: 7 },
    { src: 'alexander.jpg', name: 'Александр', age: 5 },
    { src: 'bona.jpg', name: 'Екатерина', age: 3 },
    { src: 'ichi.jpg', name: 'Анна', age: 7 },
    { src: 'lloyd.jpg', name: 'Игорь', age: 4 },
    { src: 'luiza.jpg', name: 'Луиза', age: 9 },
    { src: 'max.jpg', name: 'Maкс', age: 6 },
    { src: 'mona.jpg', name: 'Ольга', age: 3 },
    { src: 'naru.jpg', name: 'Евгения', age: 7 },
    { src: 'ramdan.jpg', name: 'Руслан', age: 8 },
    { src: 'rikki-austin.jpg', name: 'Рикки Остин', age: 3 },
    { src: 'tucker.jpg', name: 'Дмитрий', age: 9 },
    { src: 'uriel.jpg', name: 'Михаил', age: 6 },
    { src: 'zoe.jpg', name: 'Зоя', age: 2 },
  ]

